### PR TITLE
Updated list of testers to include all requested staff

### PR DESCRIPTION
**Pull request by bcmcms**

### CODE REVIEW

**Comment by caleb-james-smith** [comment]
Thanks. Do you know if this change was added to the database? The "Upload to Database" function will only work if the testers are also in the database.

**Comment by bcmcms** [comment]
Not yet. Nesta can tell you more.

**Comment by caleb-james-smith** [comment]
Ok. I have asked Jim for a list of tester names and emails.

**Comment by caleb-james-smith** [comment]
I have added the users to the database. We have tested that the new users can upload new cards.

**Pull request merged**
