### PR TITLE
added support for triggering the ngccmserver leading 0 checksum error

### PR DESCRIPTION
**Pull request by bcmcms**

### CODE REVIEW

**Comment by caleb-james-smith** [comment]
Was this tested? It may be hard to test "naturally" because we would need a Unique ID with a leading 0. I would have waited on merging this until the database has been updated to support this.

**Comment by caleb-james-smith** [comment]
Also, I think we should talk to Danny and Mark. We actually don't read unique ids directly from the server for both Teststand 1 and 2 (gui-step 1 and 2).
- Teststand 1: unique id read using server on raspberry pi
- Teststand 2: unique id read from link test mode

**Comment by caleb-james-smith** [comment]
Both the server on the raspberry pi and link test mode will provide the full unique id including leading zeros.

**Comment by bcmcms** [comment]
Yes, it was tested. Feel free to talk to Danny about it. I've confirmed this is what he wants (for now), but if that changes, I can make adjustments.

**Comment by caleb-james-smith** [comment]
But have you tested that cards can be uploaded to the database using this format?

**Comment by caleb-james-smith** [comment]
Yes, we will have to talk to Danny. I want to better understand his "use case" as in how is he planning to lookup cards in the DB. I should show him what is done for HE already. Only three bytes are unique, and those are easy to get from the ngccm server and search for.

**Pull request merged**
