### PR TITLE
Rewrote all colors to be determined in-python

### PR DESCRIPTION
**Pull request by bcmcms**
Colors are determined at the head of the code (because why not), but that can be moved if needed. Document-wide reskinning can be done quickly from there.

### CODE REVIEW

**Comment by caleb-james-smith** [comment]
Thanks!

**Comment by caleb-james-smith** [comment]
Thanks!
Right now the temperature value is white, but the other values are black. They can also be white.

**Comment by bcmcms** [comment]
Covered all existing foreground text colors that were overlooked, and standardized the button dimming behavior for all elements.

**Comment by caleb-james-smith** [comment]
Nice!!

**Pull request merged**
